<?php
echo '[
    {"imgurl":"img/splb1.webp.jpg",
    "content":"联想（Lenovo）IdeaPad320 15.6英寸 联想笔记本电脑 便...",
    "price":"￥499.00"},
    {"imgurl":"img/splb01.jpg"},
    {"imgurl":"img/splb2.webp.jpg",
    "content":"❇️【八代四核】扬天V330-15系列 15.6英寸酷睿八代四核商务...",
    "price":"￥599.00"},
    {"imgurl":"img/splb3.webp.jpg",
    "content":"满300减180三只松鼠 猪肉脯自然片150g休闲食品零食小吃靖...",
    "price":"￥29.90"},
    {"imgurl":"img/splb4.webp.jpg",
    "content":"飞利浦（PHILIPS）智能LED桌灯 办公商用商务书桌护眼学习...",
    "price":"￥1129.00"},
    {"imgurl":"img/splb4.webp.jpg",
    "content":"飞利浦（PHILIPS）智能LED桌灯 办公商用商务书桌护眼学习...",
    "price":"￥1129.00"},
    {"imgurl":"img/splb4.webp.jpg",
    "content":"飞利浦（PHILIPS）智能LED桌灯 办公商用商务书桌护眼学习...",
    "price":"￥1129.00"},
    {"imgurl":"img/splb4.webp.jpg",
     "content":"飞利浦（PHILIPS）智能LED桌灯 办公商用商务书桌护眼学习...",
     "price":"￥1129.00"},
     {"imgurl":"img/splb02.jpg"},
    {"imgurl":"img/splb4.webp.jpg",
     "content":"飞利浦（PHILIPS）智能LED桌灯 办公商用商务书桌护眼学习...",
    "price":"￥1129.00"},
    {"imgurl":"img/splb4.webp.jpg",
    "content":"飞利浦（PHILIPS）智能LED桌灯 办公商用商务书桌护眼学习...",
    "price":"￥1129.00"},
    {"imgurl":"img/splb2.webp.jpg",
    "content":"❇️【八代四核】扬天V330-15系列 15.6英寸酷睿八代四核商务...",
    "price":"￥599.00"},
    {"imgurl":"img/splb03.jpg"},
    {"imgurl":"img/splb2.webp.jpg",
    "content":"❇️【八代四核】扬天V330-15系列 15.6英寸酷睿八代四核商务...",
    "price":"￥599.00"},
    {"imgurl":"img/splb2.webp.jpg",
    "content":"❇️【八代四核】扬天V330-15系列 15.6英寸酷睿八代四核商务...",
    "price":"￥599.00"},
    {"imgurl":"img/splb4.webp.jpg",
    "content":"飞利浦（PHILIPS）智能LED桌灯 办公商用商务书桌护眼学习...",
    "price":"￥1129.00"},
    {"imgurl":"img/splb2.webp.jpg",
    "content":"❇️【八代四核】扬天V330-15系列 15.6英寸酷睿八代四核商务...",
    "price":"￥599.00"},
    {"imgurl":"img/splb2.webp.jpg",
    "content":"❇️【八代四核】扬天V330-15系列 15.6英寸酷睿八代四核商务...",
    "price":"￥599.00"},    
    {"imgurl":"img/splb2.webp.jpg",
    "content":"❇️【八代四核】扬天V330-15系列 15.6英寸酷睿八代四核商务...",
    "price":"￥599.00"},
    {"imgurl":"img/splb04.jpg"},
    {"imgurl":"img/splb05.jpg"},
    {"imgurl":"img/splb4.webp.jpg",
    "content":"飞利浦（PHILIPS）智能LED桌灯 办公商用商务书桌护眼学习...",
    "price":"￥1129.00"},
    {"imgurl":"img/splb2.webp.jpg",
    "content":"❇️【八代四核】扬天V330-15系列 15.6英寸酷睿八代四核商务...",
    "price":"￥599.00"},
    {"imgurl":"img/splb2.webp.jpg",
    "content":"❇️【八代四核】扬天V330-15系列 15.6英寸酷睿八代四核商务...",
    "price":"￥599.00"},
    {"imgurl":"img/splb2.webp.jpg",
    "content":"❇️【八代四核】扬天V330-15系列 15.6英寸酷睿八代四核商务...",
    "price":"￥599.00"}]';
?>